### ISSUE TITLE
Graceful error handling

### ISSUE THREAD

**Issue by cbacon91** [cbacon91/DiscordNameGen#28]
When the bot throws an error, it should not crash.

It should send the owner a message with the stack trace, what forced the error (if available), and stay running.

The most common error is 

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND gateway.discord.gg gateway.discord.gg:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by cbacon91** [comment]
per another developer..

`Ah, yeah you can also put in a process.on('uncaughtException',function(){}) to catch all exceptions. Bad practice, but it could help`

Something *like* that is sort of what I want, since I want uncaught exceptions to be caught and not be so catastrophic, but it is probably better to just try/catch around the Juan bot instance specifically and just have it restart if it crashes, to some limit (5x?)
